apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
  annotations:
    sidecar.jaegertracing.io/inject: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - env:
          - name: JAEGER_HOST
            value: jaeger-operator-metrics.observability.svc.cluster.local
        name: frontend
        image: mppcosta/uda-metrics-frontend:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - name: frontend
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: frontend
  name: frontend
  namespace: monitoring
  labels:
    name: frontend
    app: frontend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
    - port: frontend
      interval: 15s
      path: /metrics
  namespaceSelector:
    matchNames:
      - default
