apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial
  labels:
    app: trial
  annotations:
    sidecar.jaegertracing.io/inject: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: trial
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
      - name: trial
        image: mppcosta/uda-metrics-trial:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: trial
  labels:
    app: trial
spec:
  selector:
    app: trial
  ports:
    - name: trial
      port: 8082
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    sidecar.jaegertracing.io/inject: "true"
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: trial
  name: trial
  namespace: monitoring
  labels:
    name: trial
    app: trial
    release: prometheus
spec:
  selector:
    matchLabels:
      app: trial
  endpoints:
    - port: trial
      interval: 15s
      path: /metrics
  namespaceSelector:
    matchNames:
      - default
